#!/usr/bin/env bash
# Outputs the status of recent workflows for a several repos
# https://kodekloud.com/blog/bash-getopts/

set -e

#!/bin/bash
# Outputs the workflows for a given repo
# https://kodekloud.com/blog/bash-getopts/

NUMBER_OF_WORKFLOWS=1
REPOS=("ULL-MII-SYTWS/ull-mii-sytws.github.io" "ULL-MII-SYTWS-2425/ull-mii-sytws-2425.github.io")
JSON_FIELDS="createdAt,status"
OPTIONS="n:r:f:j:h"

function help {
  echo "Usage: gh action-status [-n <number of workflows>] [-r <comma separated list of repos>  [-f <comma separated json fields>]"
  echo 'Example:
  gh action-status -n 2 -r "ULL-MII-SYTWS/ull-mii-sytws.github.io,ULL-MII-SYTWS-2425/ull-mii-sytws-2425.github.io" -f "createdAt,status" 
  '
  echo "JSON FIELDS:
  attempt, conclusion, createdAt, databaseId, displayTitle, event, headBranch,
  headSha, name, number, startedAt, status, updatedAt, url, workflowDatabaseId,
  workflowName
  "
  exit 0
} 
# Get number of workflows from command line if provided as argument -n <number>
# Example: ./scripts/get-workflows.sh -n 5
# Get the list of repos from the command line if provided as argument -r "<repo1>,<repo2>..."
# Example: .-f "createdAt,status" -r "ULL-MII-SYTWS/ull-mii-sytws.github.io ULL-MII-SYTWS-2425/ull-mii-sytws-2425.github.io" -f "createdAt,status"
while getopts "$OPTIONS" flag
do
    case "${flag}" in
        n) NUMBER_OF_WORKFLOWS=${OPTARG};;
        r) REPOS=(${OPTARG//,/ });;
        j) JSON_FIELDS=${OPTARG};;
        f) JSON_FIELDS=${OPTARG};;
        *) help;;
    esac
done

for REPONAME in "${REPOS[@]}"; do
  echo 
  echo "REPO: $REPONAME"
  WORKFLOWID=$(gh run list --json $JSON_FIELDS -R $REPONAME -L $NUMBER_OF_WORKFLOWS)
  echo $WORKFLOWID | jq '.'
done

